### ISSUE TITLE
Enable composer runtime api 2 support

### ISSUE THREAD

**Issue by Blayew** [kellerkinderDE/K10rDeployment#12]
Hey,

since version 5.7.8 of shopware, shopware requires doctrine/orm in version 2.11.0.

Doctrine/orm requires then composer-runtime-api in version 2: https://github.com/doctrine/orm/blob/2.11.0/composer.json#L24 and this is not compatible with K10rDeployment in the latest version.

Would it be possible to update K10rDeployment to make it work with shopware version minimum 5.7.8 or is there an alternative to make it work?

BR
Maurice Fink

**Comment by lx-wnk** [comment]
Hi @Blayew, sorry for the late reply!

Unfortunately, there is nothing we can do to provide the functionality. The reason is that _doctrine_ requires _composer_ in version **2.x**, as you can check by running `composer install` inside a Shopware v5.7.8 installation. This will result in the output of:
```
Problem 1
    - doctrine/orm 2.11.0 needs composer-runtime-api ^2 -> no suitable package found.
    - doctrine/orm 2.11.0 requires composer-runtime-api ^2 -> no suitable package found.
    - Installation requirement for doctrine/orm 2.11.0 -> can be fulfilled by doctrine/orm[2.11.0].

Possible causes:
 - This package is not installable through composer 1.x, see <https://blog.packagist.com/deprecating-composer-1-support/>
```

If you upgrade composer to V2, everything should work as expected 🙂

BR
Alex

**Comment by Blayew** [comment]
Hi @jinnoflife, sorry for the late reply as well!

thank you for the informations, solution worked for me.

BG
Maurice Fink
